<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-24T16:45:38 IST" name="Default suite" finished-at="2024-03-24T16:46:02 IST" duration-ms="24434">
    <groups>
    </groups>
    <test started-at="2024-03-24T16:45:38 IST" name="Default test" finished-at="2024-03-24T16:46:02 IST" duration-ms="24434">
      <class name="Testcase.Makemytrip">
        <test-method is-config="true" signature="LaunchDriver()[pri:0, instance:Testcase.Makemytrip@515c6049]" started-at="2024-03-24T16:45:36 IST" name="LaunchDriver" finished-at="2024-03-24T16:45:38 IST" duration-ms="2058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchDriver -->
        <test-method is-config="true" signature="LaunchURL()[pri:0, instance:Testcase.Makemytrip@515c6049]" started-at="2024-03-24T16:45:38 IST" name="LaunchURL" finished-at="2024-03-24T16:45:46 IST" duration-ms="8722" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchURL -->
        <test-method signature="validSearch()[pri:0, instance:Testcase.Makemytrip@515c6049]" started-at="2024-03-24T16:45:46 IST" name="validSearch" finished-at="2024-03-24T16:45:54 IST" duration-ms="7477" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NETWORK PROBLEM ] but found [NETWORK PROBLEM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NETWORK PROBLEM ] but found [NETWORK PROBLEM]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Testcase.Makemytrip.validSearch(Makemytrip.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validSearch -->
        <test-method signature="SameCityValidation()[pri:1, instance:Testcase.Makemytrip@515c6049]" started-at="2024-03-24T16:45:54 IST" name="SameCityValidation" finished-at="2024-03-24T16:46:02 IST" duration-ms="8197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SameCityValidation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Testcase.Makemytrip@515c6049]" started-at="2024-03-24T16:46:02 IST" name="closeBrowser" finished-at="2024-03-24T16:46:02 IST" duration-ms="287" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Testcase.Makemytrip -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
